### ISSUE TITLE
what's wrong with libcyusb besides unsafe multithreading?

### ISSUE THREAD

**Issue by AleXoundOS** [hmaarrfk/libcyusb#1]
The README has a warning regardless the limited use of the library due to unsafe handling of multithreading as a consequence of immature global variables usage. What are the other limitations?

**Comment by hmaarrfk** [comment]
I added that warning because I noticed that you starred it.

Their code is full of using "static" variables
https://github.com/hmaarrfk/libcyusb/blob/master/lib/libcyusb.cpp#L47
and the hidden state is necessary for correct functionality.

They use so many configuration files, and whatnot, that mean that your code needs to fit in their paradigm.

Their functions are more or less 1 function wrappers for libusb.
You can read what their functiosn do, and just call the equivalient libusb functions.

Better support from the OSS community.

Finally, I don't think it hotswaps pretty well. Because once the detection code gets triggered, it saves the "detected" devices in a global list, and won't rescan.

It isn't even a dropin replacement for their Windows Library, so whats the point?

**Comment by AleXoundOS** [comment]
Thank you for the explanation.
